
// This file is auto-generated from docs/backend.json
// Do not edit this file directly.
import type { Timestamp } from 'firebase/firestore';

/**
 * Utility type to ensure an object has a Firestore document ID.
 */
export type WithId<T> = T & { id: string };

// --- UPDATED TENANT SETTINGS (For Multi-tenant Architecture) ---
export type TenantSettings = {
    // Identity
    barangayName: string;
    location?: { // Structured Location
        city: string;
        province: string;
        region?: string;
        zipCode?: string;
    };
    // Legacy flat fields (for backward compat)
    name?: string;
    city?: string;
    province?: string;
    region?: string;
    zipCode?: string;

    // Contact
    barangayHallAddress?: string;
    contactNumber?: string;
    email?: string;

    // Branding
    logoUrl?: string;
    cityLogoUrl?: string;
    sealUrl?: string;

    // Administration (Added for Purok Support)
    puroks?: string[]; // Array of Purok Names
    
    // Territory
    territory?: {
        boundary: {lat: number, lng: number}[];
    };

    // System Config
    settings?: {
        themeColor?: string;
        allowPublicRequests?: boolean;
        contactEmail?: string;
        contactPhone?: string;
        paperSize?: 'A4' | 'Letter';
        pickupSmsTemplate?: string;
        sosSmsTemplate?: string;
    };
    
    captainProfile?: {
        name: string;
        email: string;
    };

    createdAt?: Timestamp;
};

export type Purok = {
    purokId: string;
    name: string;
    district?: string; // Optional district name.
    description?: string;
    purokLeaderId?: string; // Foreign Key to the User ID of the assigned official.
    createdAt?: Timestamp;
};

export type Household = {
    householdId: string;
    name?: string; // A descriptive name for the household, e.g., 'Dela Cruz Family', derived from the head of household.
    householdNumber: string; // A unique identifier assigned by the barangay.
    purokId: string;
    household_head_id: string; // FK to residents.resident_id
    address: string;
    housing_material?: 'Concrete' | 'Semi-Concrete' | 'Light Material' | 'Salvaged Material';
    tenure_status?: 'Owned' | 'Rented' | 'Living with Relatives' | 'Informal Settler';
    water_source?: 'Piped' | 'Deep Well' | 'Shared Faucet' | 'Buying Water';
    toilet_facility?: 'Water-sealed' | 'Antipolo type' | 'None';
    electricity?: 'Direct Connection' | 'Sub-meter' | 'Jumper' | 'Solar/None';
    latitude?: number;
    longitude?: number;
    boundary?: {lat: number, lng: number}[]; // GeoJSON-like polygon points
    createdAt?: Timestamp;
    status?: 'Verified' | 'Unverified'; // Explicitly adding status as it's used in the app
};

export type HouseholdMember = {
    memberId: string;
    householdId: string;
    residentId: string;
    role: 'Head' | 'Spouse' | 'Child' | 'Parent' | 'Sibling' | 'Other';
};

export type Resident = {
    residentId: string;
    householdId?: string; // Reference to the household.
    firstName: string;
    lastName: string;
    dateOfBirth: string; // ISO Date string (dob)
    gender: 'Male' | 'Female' | 'Other';
    address?: string;
    purokId?: string; // Added for explicit Purok linking
    status?: 'Active' | 'Moved Out' | 'Deceased';
    middleName?: string;
    suffix?: string;
    civilStatus?: 'Single' | 'Married' | 'Widowed' | 'Separated';
    nationality?: string;
    isVoter?: boolean;
    is4ps?: boolean;
    isPwd?: boolean;
    occupation?: string;
    contactNumber?: string;
    email?: string;
    // Additive extension for Social Welfare
    vulnerability_tags?: ('PWD' | 'Solo Parent' | 'Senior' | 'Indigent' | 'Pregnant')[]; 
    is_head_of_family?: boolean;
};

export type User = {
    userId: string;
    fullName: string; // The full name of the user.
    residentId?: string; // Optional: Link to a resident profile.
    position: string; // Official title, e.g., Punong Barangay, Kagawad.
    committee?: string; // Committee chairmanship, if applicable.
    termStart?: string; // ISO Date string for start of the official's term.
    termEnd?: string; // ISO Date string for end of the official's term.
    digitalSignatureUrl?: string; // URL to the official's digital signature image.
    systemRole: 'Super Admin' | 'Encoder' | 'Viewer' | 'Responder' | 'Admin'; // Defines the user's permission level in the system.
    email: string;
    password_hash?: string;
    status: 'Active' | 'Inactive' | 'Pending';
    tenantId?: string; // Added for multi-tenant linkage
};

export type BlotterCase = {
    caseId: string;
    caseType: string; // e.g., 'Slight Physical Injuries', 'Theft (Petty)', 'Unlawful Detainer', etc.
    severity?: 'Low' | 'Medium' | 'High' | 'Admin' | 'Referral Only'; // Severity level to guide system actions.
    narrative: string;
    dateReported: Timestamp;
    filedByUserId?: string; // The user ID of the barangay official who filed the report.
    status: 'Open' | 'Under Mediation' | 'Conciliation' | 'Arbitration' | 'Settled' | 'Dismissed' | 'Referred' | 'Issued CFA';
    referredTo?: string; // Agency/office where case was referred.
    referralDate?: string; // ISO Date string for date of referral.
    complainantIds: string[];
    respondentIds: string[];
    relatedOrdinanceId?: string; // Additive extension
};

export type BlotterParticipant = {
    participantId: string;
    caseId: string;
    residentId: string;
    role: 'Complainant' | 'Respondent' | 'Witness';
};

export type CertificateType = {
    certTypeId: string;
    name: string;
    code?: string;
    fee?: number;
    validityInMonths?: number;
    requirements?: string[];
    exemptions?: string[];
    signatory?: string;
    templateId?: string;
};

export type CertificateRequest = {
    requestId: string;
    requestNumber: string;
    residentId: string;
    residentName: string;
    certTypeId: string;
    certificateName: string;
    purpose: string;
    status: 'Pending' | 'Processing' | 'Approved' | 'Ready for Pickup' | 'Claimed' | 'Denied';
    dateRequested: Timestamp;
    dateProcessed?: Timestamp;
    processedByUserId?: string;
    denialReason?: string;
};

export type FinancialTransaction = {
    transactionId: string;
    transactionType: 'Income' | 'Expense';
    amount: number;
    transaction_date: string; // ISO Date string
    payment_method?: 'Cash' | 'Check' | 'Bank Transfer' | 'GCash' | 'Maya';
    reference_number?: string; // OR Number for Income, DV/Check Number for Expense.
    payor_payee: string; // Name of the person or entity for the transaction.
    fund_source?: 'General Fund' | 'Sangguniang Kabataan (SK) Fund' | 'Gender and Development (GAD) Fund' | 'Calamity / DRRM Fund';
    category: string;
    description: string; // Particulars of the transaction.
    attachment_url?: string; // URL to the uploaded supporting document.
    status: 'Draft' | 'Pending Approval' | 'Posted' | 'Void';
    recorded_by_user?: string; // FK to the user ID who recorded the transaction.
    createdAt?: Timestamp;
};

export type Obligation = {
    obrId: string;
    obrNumber: string; // e.g., 'OBR-2025-01-001'
    payee: string; // Vendor or Resident Name
    fundSource?: 'General Fund' | 'SK Fund' | 'Calamity Fund';
    description?: string;
    amount: number;
    status?: 'Active' | 'Cancelled' | 'Fully Paid';
    certifiedBy?: string; // User ID of Treasurer
    certifiedAt?: Timestamp;
    createdAt?: Timestamp;
};

export type DisbursementVoucher = {
    dvId: string;
    dvNumber: string; // e.g., 'DV-2025-10-001'
    obrId: string; // Link to the Obligation Request
    payee: string;
    description?: string;
    fundSource?: 'General Fund' | 'Sangguniang Kabataan (SK) Fund' | 'Gender and Development (GAD) Fund' | 'Calamity / DRRM Fund';
    grossAmount: number;
    taxAmount?: number;
    netAmount: number;
    status: 'Draft' | 'For Budget Certification' | 'For Approval' | 'Ready for Payment' | 'Released' | 'Cancelled';
    checkNumber?: string;
    bankAccountId?: string;
    releasedAt?: Timestamp;
    receivedBy?: string;
};


export type Project = {
    projectId: string;
    projectName: string;
    description?: string;
    category: 'Social Services' | 'Economic Services' | 'Infrastructure' | 'Environmental Management' | 'Disaster Risk Reduction';
    purokId?: string;
    specific_location?: string;
    budget_amount: number;
    contract_amount?: number;
    source_of_fund?: '20% Barangay Development Fund (BDF)' | '10% SK Fund' | '5% BDRRM Fund' | 'General Fund / MOOE' | 'External Source';
    appropriation_year?: number;
    sb_resolution_no?: string;
    implementation_mode?: 'By Administration' | 'By Contract';
    contractor_name?: string;
    procurement_status?: 'Pre-Procurement' | 'Posting/Advertising' | 'Bid Evaluation' | 'Awarded' | 'Notice to Proceed Issued';
    target_start_date?: string; // ISO Date string
    target_end_date?: string; // ISO Date string
    actual_start_date?: string; // ISO Date string
    actual_end_date?: string; // ISO Date string
    status: 'Planned' | 'Procurement' | 'Ongoing' | 'Suspended' | 'Completed' | 'Cancelled';
    percentComplete?: number;
    manager_user_id?: string;
};

export type Program = {
    programId: string;
    name: string;
    description?: string;
    category: 'General Administration' | 'Social Services' | 'Economic Services' | 'Other Services';
};

export type EmergencyAlert = {
    alertId: string;
    residentId: string;
    residentName?: string;
    timestamp: Timestamp;
    latitude: number;
    longitude: number;
    accuracy_m?: number; // Added: GPS accuracy
    location_source?: 'GPS' | 'Manual' | 'Simulation'; // Added: Source
    status: 'New' | 'Acknowledged' | 'Dispatched' | 'On Scene' | 'Resolved' | 'False Alarm';
    category?: 'Medical' | 'Fire' | 'Crime' | 'Accident' | 'Unspecified';
    description?: string; // Admin's notes on the situation.
    message?: string; // Resident's message.
    contactNumber?: string;
    householdId?: string;
    householdMembersSnapshot?: { name: string; age?: string; relationship?: string }[];
    responder_team_id?: string; // ID of the responding user or vehicle.
    responderDetails?: {
        userId: string;
        name: string;
        contactNumber: string;
        vehicleInfo?: string;
    };
    acknowledgedByUserId?: string;
    resolvedAt?: Timestamp;
    notes?: string;
};

export type IncidentLog = {
    logId: string;
    alertId: string;
    userId: string; // Who took the action (Admin or Tanod).
    action_taken: 'ACKNOWLEDGED' | 'DISPATCHED' | 'ARRIVED' | 'RESOLVED';
    notes?: string;
    timestamp?: Timestamp;
};

export type ResponderLocation = {
    userId: string; // The Tanod's user ID.
    latitude: number;
    longitude: number;
    accuracy?: number; // Added
    last_active: Timestamp;
    status: 'On Duty' | 'Busy' | 'Offline';
};

export type DocumentTemplate = {
    templateId: string;
    name: string;
    description?: string;
    content: string; // HTML content
    createdAt?: Timestamp;
    updatedAt?: Timestamp;
};

export type Announcement = {
    announcementId: string;
    title: string;
    content?: string;
    imageUrl?: string;
    category: 'General Info' | 'Event' | 'Health' | 'Ordinance' | 'Emergency';
    datePosted: Timestamp;
    postedByUserId: string;
    // New fields for events
    eventDate?: string; // ISO Date string
    eventTime?: string; // Time string
    eventLocation?: string;
    contactPerson?: string;
    contactNumber?: string;
    registrationLink?: string;
};

export type Pet = {
    petId: string;
    ownerResidentId: string;
    householdId?: string;
    name: string;
    species: 'Dog' | 'Cat' | 'Other';
    breed?: string;
    colorMarkings?: string;
    gender?: 'Male' | 'Female';
    dateOfBirth?: string; // ISO Date string
    photoUrl?: string; // URL to the pet's photo
    tagNumber?: string;
    microchipNumber?: string;
    isNeutered?: boolean;
    behaviorStatus?: 'Friendly / Docile' | 'Territorial / Guard Dog' | 'History of Biting (Aggressive)';
    status?: 'Active' | 'Deceased' | 'Lost' | 'Transferred';
    createdAt?: Timestamp;
};

export type PetVaccination = {
    vaccinationId: string;
    petId: string;
    vaccineType?: string;
    dateAdministered: string; // ISO Date string
    dateExpiration: string; // ISO Date string
    veterinarian?: string;
    batchNumber?: string;
    remarks?: string;
};

export type FacilityResource = {
    resourceId: string;
    name: string; // e.g., 'Session Hall', 'Ambulance'
    type: 'Room' | 'Vehicle' | 'Equipment';
    status?: 'Available' | 'Under Maintenance';
};

export type ScheduleEvent = {
    eventId: string;
    category: 'Blotter' | 'Health' | 'Session' | 'Rental' | 'Public';
    title: string;
    description?: string;
    referenceId?: string; // Link to the source (e.g., Blotter Case ID).
    start: string; // Start datetime in ISO 8601 format.
    end: string; // End datetime in ISO 8601 format.
    allDay?: boolean;
    resourceId?: string; // FK to the Facility/Resource being booked.
    status?: 'Scheduled' | 'Completed' | 'Cancelled' | 'Rescheduled';
    createdByUserId?: string;
};

export type EventAttendee = {
    attendanceId: string;
    eventId: string;
    residentId?: string;
    staffId?: string;
    customName?: string; // For non-resident guests.
    role?: string; // e.g., Complainant, Patient, Guest.
    notificationSent?: boolean;
    attendanceStatus?: 'Pending' | 'Present' | 'Absent' | 'Excused';
};

export type Barangay = {
  barangayId: string;
  name: string;
  city: string;
  province: string;
};

// --- NEW TYPES FOR SOCIAL WELFARE ---
export type AidProgram = {
  programId: string;
  title: string;
  type: 'Cash' | 'Goods';
  budgetAllocated: number;
  status: 'Active' | 'Completed' | 'Archived';
  eligibilityCriteria: string[]; // e.g., ["PWD", "Senior"]
  startDate: Timestamp;
  endDate: Timestamp;
  createdAt: Timestamp;
};

export type AidClaim = {
  claimId: string;
  programId: string;
  residentId: string;
  householdId: string;
  status: 'Pending' | 'Approved' | 'Released' | 'Rejected';
  amountOrValue: number;
  dateClaimed: Timestamp;
  releasedBy?: string;
  notes?: string;
};

// --- NEW TYPES FOR LEGISLATIVE (Phase 2) ---
export type Ordinance = {
    ordinanceId: string;
    ordinanceNumber: string; // e.g., "Ord-2024-001"
    title: string;
    description: string; // Storing content here as per plan, or use new field
    contentHtml?: string; // Additive: Rich text content
    category: 'Curfew' | 'Noise' | 'Sanitation' | 'Traffic' | 'General';
    penaltyAmount: number;
    pdfUrl?: string; // Link to storage
    dateEnacted: string; // ISO Date string
    status: 'Active' | 'Repealed' | 'Pending' | 'Draft'; // Added Draft
    createdAt: Timestamp;
    relatedViolation?: string;
};

// --- NEW TYPES FOR ASSETS & FLEET (Phase 3) ---
export type FixedAsset = {
  assetId: string;
  name: string; // e.g., "Barangay Patrol 01"
  type: 'Vehicle' | 'Equipment' | 'Facility' | 'Furniture';
  status: 'Available' | 'In Use' | 'Maintenance' | 'Decommissioned' | 'Damaged' | 'Deployed' | 'Under Repair' | 'Condemned';
  purchaseDate: string; // ISO Date string
  serialNumber?: string;
  photoUrl?: string; // Added as per requirements

  // Location and Custodian
  location?: string; // e.g., "Barangay Hall Storage", "Health Center"
  custodianId?: string; // Link to User or Resident
  custodianName?: string; // Denormalized name for easier display

  // Fleet specific fields
  brand?: string;
  model?: string;
  plateNumber?: string; 
  chassisNumber?: string;
  engineNumber?: string;
  lastMaintenanceDate?: string; // ISO Date string
  nextMaintenanceDue?: string; // ISO Date string
  odometerReading?: number;
  
  createdAt: Timestamp;
};

export type AssetBooking = {
  bookingId: string;
  assetId: string;
  assetName: string; // Denormalized for easy display
  borrowerName: string; // Or link to residentId
  residentId?: string; // Optional link
  purpose: string;
  startDateTime: string; // ISO
  endDateTime: string; // ISO
  status: 'Pending' | 'Approved' | 'Returned' | 'Overdue' | 'Rejected';
  approvedBy?: string; // User ID
  createdAt: Timestamp;
  
  // Logistics & Accountability
  destination?: string; // For vehicles
  driverId?: string; // For vehicles
  driverName?: string;
  startOdometer?: number;
  endOdometer?: number;
};

export type MaintenanceLog = {
    logId: string;
    assetId: string; // FK to FixedAsset
    serviceDate: string; // ISO Date string
    serviceType: string; // e.g., "Change Oil", "Tire Replacement", "Repair"
    description: string; // Detailed reason for maintenance
    partsUsed?: string; // Comma-separated list of parts
    servicedBy?: string; // Name of shop or mechanic
    cost: number;
    odometerReading?: number;
    receiptUrl?: string;
    notes?: string; // General notes
    createdAt: Timestamp;
};


// Deprecated old types. To be removed after full refactoring.
export type Blotter = BlotterCase;
export type Document = CertificateRequest;
export type Financial = FinancialTransaction;
// The old User type is now fully replaced. We keep a stub for dependent files.
// export type OldUser = { userId: string, roleId: string, username: string, status: string, residentId?: string, password_hash?: string };
